---
version: "3"
services:
  openssh-server:
    image: lscr.io/linuxserver/openssh-server
    container_name: lab
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
      - USER_PASSWORD=passw0rd
      - USER_NAME=codesenju
      - PASSWORD_ACCESS=true 
      - HOSTNAME=lab
    ports:
      - 2222:2222
    restart: unless-stopped